"""Adapt the existing D-drive SPA to the additive banking API contract."""
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]/'.runtime/phase3-source'
def replace(path,old,new):
    file=ROOT/path
    text=file.read_text(encoding='utf-8')
    if new in text: return
    if old not in text: raise ValueError(f'Missing expected source in {path}')
    file.write_text(text.replace(old,new),encoding='utf-8')

replace('src/components/Login.tsx',"icon:Layers3}].map", "icon:Layers3},{id:'compliance_officer',label:'compliance',description:'complianceDescription',icon:ShieldCheck},{id:'branch_analyst',label:'branch',description:'branchDescription',icon:ChartNoAxesCombined},{id:'fraud_investigator',label:'fraud',description:'fraudDescription',icon:LockKeyhole}].map")
replace('src/components/Workspace.tsx',"  const quick=claims.role==='sales_analyst'?['sampleSales','sampleCountry'] as const:['sampleInventory','sampleArtists'] as const;", "  const roleLabel={sales_analyst:'sales',inventory_lead:'inventory',compliance_officer:'compliance',branch_analyst:'branch',fraud_investigator:'fraud'} as const;\n  const quickByRole={sales_analyst:['sampleSales','sampleCountry'],inventory_lead:['sampleInventory','sampleArtists'],compliance_officer:['sampleKyc','sampleCash'],branch_analyst:['sampleBalance','sampleLoans'],fraud_investigator:['sampleFlagged','sampleCards']} as const;\n  const quick=quickByRole[claims.role];\n  const banking=['compliance_officer','branch_analyst','fraud_investigator'].includes(claims.role);\n  const dialect=schema?.dialect==='postgres'||banking?'PostgreSQL':'T-SQL';")
replace('src/components/Workspace.tsx',"{claims.role==='sales_analyst'?t('sales'):t('inventory')}","{t(roleLabel[claims.role])}")
replace('src/components/Workspace.tsx',"/> Chinook <code>T-SQL</code>","/> {banking?'FinCore Enterprise':'Chinook'} <code>{dialect}</code>")
replace('src/components/Workspace.tsx',"<span>SQL / T-SQL</span>","<span>SQL / {dialect}</span>")

replace('src/i18n.ts',"tsql:'T-SQL · active engine',postgres:'PostgreSQL · migration planned'","tsql:'T-SQL · legacy engine',postgres:'PostgreSQL · FinCore adapter'")
replace('src/i18n.ts',"footerNote:'Built for enterprise analytics. Banking schema and PostgreSQL migration are subsequent rollout stages.'","footerNote:'FinCore banking analytics and legacy compatibility. Database access requires administrator provisioning.'")
replace('src/i18n.ts',"tsql:'T-SQL · المحرك النشط',postgres:'PostgreSQL · ترحيل مخطط'","tsql:'T-SQL · المحرك السابق',postgres:'PostgreSQL · محوّل FinCore'")
replace('src/i18n.ts',"footerNote:'مصممة للتحليلات المؤسسية. مخطط الخدمات المصرفية وترحيل PostgreSQL ضمن مراحل النشر التالية.'","footerNote:'تحليلات FinCore المصرفية مع توافق النظام السابق. يتطلب الوصول إعداداً من مسؤول النظام.'")
replace('src/i18n.ts',"  identity:'Corporate identity'","  compliance:'Compliance officer',branch:'Branch analyst',fraud:'Fraud investigator',complianceDescription:'KYC, cash monitoring and risk',branchDescription:'Assigned branch balances and loans',fraudDescription:'Flagged activity in assigned active cases',\n  sampleKyc:'Show KYC reviews',sampleCash:'Show high-risk cash monitoring',sampleBalance:'Show daily account balances',sampleLoans:'Show loan delinquency and interest accrual',sampleFlagged:'Show flagged transactions',sampleCards:'Show card events',\n  identity:'Corporate identity'")
replace('src/i18n.ts',"  signIn:'الدخول إلى مساحة العمل'","  compliance:'مسؤول الامتثال',branch:'محلل الفروع',fraud:'محقق الاحتيال',complianceDescription:'مراجعات الهوية والنقد والمخاطر',branchDescription:'أرصدة وقروض الفروع المعيّنة',fraudDescription:'النشاط المشبوه في القضايا النشطة المعيّنة',sampleKyc:'Show KYC reviews',sampleCash:'Show high-risk cash monitoring',sampleBalance:'Show daily account balances',sampleLoans:'Show loan delinquency and interest accrual',sampleFlagged:'Show flagged transactions',sampleCards:'Show card events',\n  signIn:'الدخول إلى مساحة العمل'")
replace('README.md',"`openapi.json` is the additive Phase 3 contract exported by `deploy_bundle/tools/export_phase03_openapi.py`. That exporter verifies every Phase 2 component schema remains identical.","`openapi.json` is the additive Phase 4 contract exported by `deploy_bundle/tools/export_phase04_openapi.py`. Existing REST paths, query requests and output shapes remain unchanged; the role enumeration adds three banking personas and schema dialect adds `postgres`.")
replace('README.md',"The active database engine remains T-SQL/Chinook. PostgreSQL and the FinCore banking schema are labeled as planned migrations. FinTech positioning describes the product's controls rather than claiming those later migrations are deployed.","Banking accounts select the PostgreSQL/FinCore engine on the server; the original two roles retain T-SQL/Chinook compatibility. The portal exposes all five personas without letting browser selection grant access. Schema and SQL panels use the server dialect. Banking shortcuts use approved registry v1 English requests, including in the Arabic layout; unknown filters and financial formulas fail closed. See `D:/BIRD-Interact/deploy_bundle/docs/FINCORE_SCHEMA.md` for migration and private `SENTINEL_PG_AUTH_FILE` provisioning. PostgreSQL access is never inferred from demo mode. Native PostgreSQL integration is verified locally; cloud deployment remains a subsequent phase.")
print('Banking role portal, dialect labels and approved financial shortcuts prepared.')
