import { useMemo, useRef, useState } from 'react';
import { useVirtualizer } from '@tanstack/react-virtual';
import { ArrowDownUp, Download, ChevronLeft, ChevronRight, Table2 } from 'lucide-react';
import { compareCells, csv, download, excel } from '../lib/data';
import type { Translator } from '../i18n';
import { Button } from './ui';
export function DataGrid({columns,rows,t}:{columns:string[];rows:unknown[][];t:Translator}){
  const [sort,setSort]=useState<{column:number;desc:boolean}|null>(null),[page,setPage]=useState(0),[exporting,setExporting]=useState(false),[error,setError]=useState('');
  const viewport=useRef<HTMLDivElement>(null);
  const sorted=useMemo(()=>sort?[...rows].sort((a,b)=>compareCells(a[sort.column],b[sort.column])*(sort.desc?-1:1)):rows,[rows,sort]);
  const pages=Math.max(1,Math.ceil(sorted.length/100));const currentPage=Math.min(page,pages-1);const visible=sorted.slice(currentPage*100,(currentPage+1)*100);
  const virtual=useVirtualizer({count:visible.length,getScrollElement:()=>viewport.current,estimateSize:()=>39,overscan:8});
  const template=`repeat(${Math.max(1,columns.length)}, minmax(150px, 1fr))`;
  const exportExcel=async()=>{setExporting(true);setError('');try{await excel(columns,sorted);}catch{setError(t('requestError'));}finally{setExporting(false);}};
  return <div className="grid-panel"><div className="panel-header"><h3><Table2 size={15}/>{t('data')}<span>{rows.length}</span></h3><div title={t('totalRows')}><Button variant="ghost" disabled={!rows.length} onClick={()=>download(new Blob([csv(columns,sorted)],{type:'text/csv;charset=utf-8'}),'sentinel-results.csv')}><Download size={13}/>{t('exportCSV')}</Button><Button variant="ghost" disabled={!rows.length||exporting} onClick={()=>void exportExcel()}>{t(exporting?'exporting':'exportExcel')}</Button></div></div>{error&&<div role="alert" className="error-banner">{error}</div>}<div className="data-scroll" ref={viewport} role="grid" aria-label={t('data')} aria-rowcount={rows.length+1} aria-colcount={columns.length}><div className="grid-head" role="row" style={{gridTemplateColumns:template}}>{columns.map((column,index)=><div role="columnheader" aria-sort={sort?.column===index?(sort.desc?'descending':'ascending'):'none'} key={column+index}><button onClick={()=>{setSort({column:index,desc:sort?.column===index?!sort.desc:false});setPage(0);}}>{column}<ArrowDownUp size={12}/></button></div>)}</div><div className="virtual-body" style={{height:virtual.getTotalSize(),minWidth:columns.length*150}}>{virtual.getVirtualItems().map(item=><div key={item.key} role="row" aria-rowindex={currentPage*100+item.index+2} className="grid-row" style={{gridTemplateColumns:template,transform:`translateY(${item.start}px)`}}>{visible[item.index].map((value,index)=><div role="gridcell" key={index} title={String(value??'')} className={typeof value==='number'||/^[-\d.]+$/.test(String(value))?'numeric-cell':''}>{value==null?<span className="null-cell">NULL</span>:String(value)}</div>)}</div>)}</div>{!rows.length&&<div className="empty-grid"><Table2 size={28}/><strong>{t('empty')}</strong><span>{t('emptyBody')}</span></div>}</div><div className="grid-pagination"><span>{rows.length} {t('rows')}</span><div><Button variant="ghost" disabled={currentPage===0} aria-label={t('previous')} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={14}/></Button><span>{t('page')} {currentPage+1} {t('of')} {pages}</span><Button variant="ghost" disabled={currentPage===pages-1} aria-label={t('next')} onClick={()=>setPage(currentPage+1)}><ChevronRight size={14}/></Button></div></div></div>;
}
