import { useState, type FormEvent } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { X, LockKeyhole, ChartNoAxesCombined, Layers3, ArrowRight, ShieldCheck } from 'lucide-react';
import { api, ApiError, type Session } from '../api/client';
import type { Translator } from '../i18n';
import { Button } from './ui';
export function Login({open,onOpenChange,onSession,t}:{open:boolean;onOpenChange:(open:boolean)=>void;onSession:(session:Session)=>void;t:Translator}){
  const [role,setRole]=useState('sales_analyst'),[identity,setIdentity]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const session=await api.login(identity,password);setPassword('');onSession(session);onOpenChange(false);}catch(error){setError(error instanceof ApiError?error.message:t('networkError'));}finally{setBusy(false);}};
  return <Dialog.Root open={open} onOpenChange={value=>{onOpenChange(value);if(!value){setPassword('');setError('');}}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="login-dialog"><div className="login-brand-icon"><ShieldCheck size={25}/></div><Dialog.Title>{t('signIn')}</Dialog.Title><Dialog.Description>{t('signInDescription')}</Dialog.Description><Dialog.Close className="dialog-close" aria-label={t('close')}><X size={18}/></Dialog.Close><div className="role-options">{[{id:'sales_analyst',label:'sales',description:'salesDescription',icon:ChartNoAxesCombined},{id:'inventory_lead',label:'inventory',description:'inventoryDescription',icon:Layers3},{id:'compliance_officer',label:'compliance',description:'complianceDescription',icon:ShieldCheck},{id:'branch_analyst',label:'branch',description:'branchDescription',icon:ChartNoAxesCombined},{id:'fraud_investigator',label:'fraud',description:'fraudDescription',icon:LockKeyhole}].map(item=><button key={item.id} aria-pressed={role===item.id} onClick={()=>setRole(item.id)}><item.icon size={20}/><strong>{t(item.label as 'sales')}</strong><span>{t(item.description as 'salesDescription')}</span></button>)}</div><form onSubmit={submit}><label>{t('identity')}<input required name="identity" autoComplete="username" maxLength={128} value={identity} onChange={event=>setIdentity(event.target.value)} dir="ltr"/></label><label>{t('password')}<input required name="password" autoComplete="current-password" type="password" maxLength={1024} value={password} onChange={event=>setPassword(event.target.value)} dir="ltr"/></label>{error&&<div className="error-banner" role="alert">{error}</div>}<Button type="submit" disabled={busy}><LockKeyhole size={16}/>{t(busy?'authenticating':'authenticate')}<ArrowRight size={16}/></Button></form><p className="login-policy"><ShieldCheck size={13}/>{t('serverRole')}</p></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
