import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import { Activity, ArrowRight, ChevronDown, ChevronRight, Code2, Database, Fingerprint, KeyRound, Layers3, LogOut, Mic, Play, RefreshCw, ShieldCheck, Square, Terminal, Timer, Rows3 } from 'lucide-react';
import { api, ApiError, type Job, type Schema, type Session, type Trace } from '../api/client';
import { QueryStream } from '../api/stream';
import type { Language, Translator } from '../i18n';
import { Brand, Button, LanguageButton, CopyButton, SQLCode } from './ui';
import { DataGrid } from './DataGrid';
const ChartPanel=lazy(()=>import('./ChartPanel'));
type Recognition={lang:string;continuous:boolean;interimResults:boolean;start:()=>void;stop:()=>void;onresult:(event:{results:{[index:number]:{[index:number]:{transcript:string}}}})=>void;onerror:()=>void;onend:()=>void};
export function Workspace({session,t,language,onLanguage,onLogout}:{session:Session;t:Translator;language:Language;onLanguage:()=>void;onLogout:()=>void}){
  const [schema,setSchema]=useState<Schema|null>(null),[schemaError,setSchemaError]=useState(''),[expanded,setExpanded]=useState<string[]>([]),[schemaVersion,setSchemaVersion]=useState(0);
  const [question,setQuestion]=useState(''),[job,setJob]=useState<Job|null>(null),[events,setEvents]=useState<Trace[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[intent,setIntent]=useState(''),[help,setHelp]=useState(''),[transport,setTransport]=useState('stream'),[rows,setRows]=useState<unknown[][]>([]),[columns,setColumns]=useState<string[]>([]),[jobId,setJobId]=useState(''),[listening,setListening]=useState(false);
  const stream=useRef<QueryStream|null>(null),abort=useRef<AbortController|null>(null),input=useRef<HTMLTextAreaElement>(null),recognition=useRef<Recognition|null>(null);
  const token=session.access_token;const claims=session.session;
  useEffect(()=>{const controller=new AbortController();setSchemaError('');void api.schema(token,controller.signal).then(data=>{setSchema(data);setExpanded(data.tables.slice(0,1).map(table=>table.name));}).catch(error=>{if(controller.signal.aborted)return;if(error instanceof ApiError&&error.status===401){onLogout();return;}setSchemaError(t('schemaError'));});return()=>controller.abort();},[token,schemaVersion]);
  useEffect(()=>()=>{stream.current?.close();abort.current?.abort();recognition.current?.stop();},[]);
  useEffect(()=>{const timer=setInterval(()=>{if(Date.now()/1000>=claims.expires_at)onLogout();},1000);return()=>clearInterval(timer);},[claims.expires_at]);
  const finish=(result:Job)=>{setJob(result);setJobId(result.job_id);setBusy(false);setStatus(result.status==='completed'?'complete':result.status==='cancelled'?'cancelled':'failed');if(result.output){setRows(result.output.rows);setColumns(result.output.columns);}if(result.error)setError(`${result.error.error_code}: ${result.error.detail}`);};
  const run=async()=>{
    if(busy||!question.trim())return;stream.current?.close();setBusy(true);setError('');setJob(null);setRows([]);setColumns([]);setEvents([]);setHelp('');setJobId('');setStatus('connecting');
    const controller=abort.current=new AbortController();
    try{
      const classified=await api.classify(token,question.trim(),controller.signal);setIntent(classified.intent);
      if(classified.intent!=='DATA_QUERY'){setHelp(classified.response??'');setStatus(classified.intent==='HELP'?'complete':'failed');setBusy(false);return;}
      if(transport==='stream'){
        stream.current=new QueryStream(token,question.trim(),{event:event=>setEvents(previous=>[...previous.filter(item=>item.sequence!==event.sequence),event].sort((a,b)=>a.sequence-b.sequence).slice(-256)),
          rows:(offset,headers,batch)=>{setColumns(headers);setRows(previous=>{const next=[...previous];batch.forEach((row,index)=>next[offset+index]=row);return next;});},
          result:finish,state:setStatus,job:setJobId,error:(message,code)=>{if(code==='INVALID_SESSION'||code==='AUTHENTICATION_REQUIRED'){onLogout();return;}setError(message);setBusy(false);setStatus('failed');}});
        stream.current.connect();
      }else{
        const result=await api.execute(token,question.trim(),controller.signal);finish(result);
        const audit=await api.audit(token,result.job_id);setEvents(audit.events);
      }
    }catch(error){
      if(error instanceof ApiError){if(error.status===401){onLogout();return;}setError(`${error.body.error_code}: ${error.message}`);setEvents(error.body.ast_trace??[]);if(error.body.job_id)setJobId(error.body.job_id);}
      else if(controller.signal.aborted)setStatus('cancelled');else setError(t('networkError'));
      setBusy(false);
    }
  };
  const cancel=()=>{if(transport==='stream'&&stream.current?.cancel())return;abort.current?.abort();setBusy(false);setStatus('cancelled');};
  const dictate=()=>{if(import.meta.env.VITE_ENABLE_VOICE_INPUT!=='true')return;const provider=(window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition});const Constructor=provider.SpeechRecognition??provider.webkitSpeechRecognition;if(!Constructor){setError(t('voiceUnavailable'));return;}if(listening){recognition.current?.stop();return;}const instance=recognition.current=new Constructor();instance.lang=language==='ar'?'ar-EG':'en-US';instance.continuous=false;instance.interimResults=false;instance.onresult=event=>setQuestion(value=>(value+' '+event.results[0][0].transcript).trim().slice(0,4000));instance.onerror=()=>setListening(false);instance.onend=()=>setListening(false);instance.start();setListening(true);};
  const roleLabel={sales_analyst:'sales',inventory_lead:'inventory',compliance_officer:'compliance',branch_analyst:'branch',fraud_investigator:'fraud'} as const;
  const quickByRole={sales_analyst:['sampleSales','sampleCountry'],inventory_lead:['sampleInventory','sampleArtists'],compliance_officer:['sampleKyc','sampleCash'],branch_analyst:['sampleBalance','sampleLoans'],fraud_investigator:['sampleFlagged','sampleCards']} as const;
  const quick=quickByRole[claims.role];
  const banking=['compliance_officer','branch_analyst','fraud_investigator'].includes(claims.role);
  const dialect=schema?.dialect==='postgres'||banking?'PostgreSQL':'T-SQL';
  const diffs=events.filter(event=>typeof event.details?.sql_diff==='string').map(event=>String(event.details!.sql_diff)).join('\n\n');
  const verified=events.filter(event=>event.details?.ast_verdict==='PASS'||event.details?.schema_grounding==='PASS').length;
  return <div className="workspace-app"><header className="workspace-header"><Brand compact/><div className="workspace-breadcrumb"><span>/</span>{t('workspace')}<span>/</span><strong>{t(roleLabel[claims.role])}</strong></div><div className="workspace-user"><LanguageButton language={language} onChange={onLanguage}/><span className="user-identity"><Fingerprint size={14}/>{claims.user_id}</span><Button variant="ghost" onClick={onLogout} aria-label={t('logout')}><LogOut size={16}/></Button></div></header>
    <div className="workspace-layout"><aside className="schema-sidebar"><div className="sidebar-heading"><Database size={16}/><h2>{t('schema')}</h2><Button variant="ghost" aria-label={t('retry')} onClick={()=>setSchemaVersion(value=>value+1)}><RefreshCw size={13}/></Button></div><div className="database-label"><span className="status-dot"/> {banking?'FinCore Enterprise':'Chinook'} <code>{dialect}</code></div>{!schema&&!schemaError&&<p className="sidebar-message">{t('schemaLoading')}</p>}{schemaError&&<div className="sidebar-message">{schemaError}<button onClick={()=>setSchemaVersion(value=>value+1)}>{t('retry')}</button></div>}
      <div className="schema-tables">{schema?.tables.map(table=><div className="schema-table" key={table.name}><button className="table-toggle" aria-expanded={expanded.includes(table.name)} onClick={()=>setExpanded(value=>value.includes(table.name)?value.filter(name=>name!==table.name):[...value,table.name])}>{expanded.includes(table.name)?<ChevronDown size={13}/>:<ChevronRight size={13}/>}<Layers3 size={14}/><strong>{table.name}</strong><span>{table.columns.length}</span></button>{expanded.includes(table.name)&&<ul>{table.columns.map(column=><li key={column.name} title={`${column.data_type} · ${column.nullable?'nullable':'not null'}`}>{column.primary_key?<KeyRound size={11}/>:<span className="column-dot"/>}<span>{column.name}</span><code>{column.data_type.toLowerCase().replace(/\(.*/, '')}</code></li>)}</ul>}</div>)}</div>
      {Boolean(schema?.relationships.length)&&<div className="relationship-list"><span className="micro-label">{t('relationships')}</span>{schema!.relationships.map((edge,index)=><div key={index} dir="ltr"><span>{edge.from_table}.{edge.from_column}</span><ArrowRight size={11}/><span>{edge.to_table}.{edge.to_column}</span></div>)}</div>}
      <div className="sidebar-policy"><ShieldCheck size={16}/><strong>{t('authenticated')}</strong><p>{t('restricted')}</p><span>{t('expires')} <time>{new Date(claims.expires_at*1000).toLocaleTimeString(language,{hour:'2-digit',minute:'2-digit'})}</time></span></div></aside>
    <main className="workspace-main"><div className="workspace-title"><div><span className="micro-label">SENTINEL CONTROL PLANE</span><h1>{t('overview')}</h1></div><span className="workspace-role"><ShieldCheck size={13}/>{claims.role}</span></div><div className="workspace-stats">{[{icon:Rows3,label:'rows',value:rows.length},{icon:Timer,label:'duration',value:job?.output?`${Math.round(job.output.execution_time_ms)} ms`:'—'},{icon:ShieldCheck,label:'policyChecks',value:verified},{icon:Database,label:'scope',value:claims.allowed_tables.length}].map(item=><div key={item.label}><span><item.icon size={14}/>{t(item.label as 'rows')}</span><strong>{item.value}</strong></div>)}</div>
    <section className="studio-panel"><div className="panel-header"><h2><Terminal size={16}/>{t('studio')}</h2><div className="transport-switch">{['stream','rest'].map(mode=><button key={mode} disabled={busy} aria-pressed={transport===mode} onClick={()=>setTransport(mode)}>{t(mode as 'stream')}</button>)}</div></div><Tabs.Root defaultValue="request"><Tabs.List className="studio-tabs" aria-label={t('studio')}><Tabs.Trigger value="request">{t('request')}</Tabs.Trigger><Tabs.Trigger value="sql">{t('verifiedSQL')}</Tabs.Trigger><Tabs.Trigger value="diff">{t('diff')}{diffs&&<span>1</span>}</Tabs.Trigger></Tabs.List><Tabs.Content value="request"><div className="question-input"><label className="sr-only" htmlFor="question">{t('question')}</label><textarea ref={input} id="question" maxLength={4000} value={question} onChange={event=>setQuestion(event.target.value)} placeholder={t('placeholder')} disabled={busy} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();void run();}}}/><div className="question-actions"><span>{question.length}/4000 <kbd>Ctrl ↵</kbd></span><div><Button variant="ghost" aria-label={t('voice')} className={listening?'recording':''} onClick={dictate} disabled={busy||import.meta.env.VITE_ENABLE_VOICE_INPUT!=='true'}><Mic size={16}/></Button>{busy?<Button variant="secondary" onClick={cancel}><Square size={13}/>{t('cancel')}</Button>:<Button onClick={()=>void run()} disabled={!question.trim()}><Play size={14}/>{t('run')}</Button>}</div></div></div><div className="quick-queries"><span className="micro-label">{t('quickQueries')}</span>{quick.map(key=><button key={key} disabled={busy} onClick={()=>{setQuestion(t(key));input.current?.focus();}}>{t(key)}<ArrowRight size={11}/></button>)}</div></Tabs.Content><Tabs.Content value="sql"><div className="code-toolbar"><span>SQL / {dialect}</span><CopyButton text={job?.output?.final_sql??''} t={t}/></div>{job?.output?<SQLCode sql={job.output.final_sql}/>:<p className="code-placeholder">{t('noSQL')}</p>}</Tabs.Content><Tabs.Content value="diff"><div className="code-toolbar"><span>UNIFIED DIFF</span><CopyButton text={diffs} t={t}/></div>{diffs?<SQLCode sql={diffs} diff/>:<p className="code-placeholder">{t('noDiff')}</p>}</Tabs.Content></Tabs.Root>{intent&&<div className="intent-bar"><Code2 size={13}/>{t('classified')} <code>{intent}</code><span className={busy?'busy-dot':''}/>{status?t(status in ({connected:1,connecting:1,reconnecting:1,complete:1,failed:1,cancelled:1})?status as 'complete':'running'):''}</div>}</section>
    {error&&<div role="alert" className="error-banner"><ShieldCheck size={16}/>{error}</div>}{help&&<div className="help-response">{help}</div>}
    <div className="results-layout"><div className="results-column">{columns.length||job?.status==='completed'?<><DataGrid columns={columns} rows={rows} t={t}/><Suspense fallback={<div className="chart-panel"/>}><ChartPanel columns={columns} rows={rows} t={t}/></Suspense></>:<div className="workspace-empty"><span className="empty-icon"><Code2 size={30}/></span><h2>{t('noResult')}</h2><p>{t('noResultBody')}</p><span>NL → SQL → AST → DATA</span></div>}</div><aside className="telemetry-panel"><div className="panel-header"><h3><Activity size={15}/>{t('telemetry')}</h3><span className="telemetry-count">{events.length} {t('eventCount')}</span></div>{jobId&&<div className="telemetry-job"><span>{t('queryId')}</span><code title={jobId}>{jobId.slice(0,8)}</code></div>}<div className="event-list" aria-live="polite">{!events.length?<p className="telemetry-empty">{t('noEvents')}</p>:events.map(event=><div className={`event event-${event.status}`} key={event.sequence}><span className="event-dot"/><div><div className="event-top"><strong>{event.agent}</strong><span>{event.duration_ms!=null?`${Math.round(event.duration_ms)} ms`:`#${event.sequence}`}</span></div><p>{event.message}</p>{Object.entries(event.details??{}).filter(([key])=>['ast_verdict','schema_grounding','verdict','error_code'].includes(key)).map(([key,value])=><code className="event-verdict" key={key}>{String(value??'')}</code>)}</div></div>)}</div><div className="telemetry-footer"><LockBadge/>{t('traceable')}</div></aside></div>
    </main></div></div>;
}
function LockBadge(){return <ShieldCheck size={13}/>;}
