import { chromium, expect } from '@playwright/test';
import { existsSync } from 'node:fs';
import fs from 'node:fs/promises';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..');
const folder=resolve(root,'.runtime/screenshots');await fs.mkdir(folder,{recursive:true});
const executable=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Google/Chrome/Application/chrome.exe'].find(existsSync);
if(!executable)throw new Error('A local Edge/Chrome installation is required for visual verification.');
const context=await chromium.launchPersistentContext(resolve(root,'.runtime/browser-profile'),{executablePath:executable,headless:true,viewport:{width:1440,height:1000},acceptDownloads:true,args:['--disable-gpu','--no-first-run','--disable-background-networking']});
await context.addInitScript(()=>{try{localStorage.removeItem('sentinel-language');}catch{}});
const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
const report={};
try{
  await page.goto('http://localhost:5173',{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
  await expect(page.getByText('API operational',{exact:true})).toBeVisible();
  await page.screenshot({path:resolve(folder,'landing-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Run simulation',exact:true}).click();await expect(page.getByText('Intercepted',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Legitimate profit',exact:true}).click();await page.getByRole('button',{name:'Run simulation',exact:true}).click();await expect(page.getByText('Verified',{exact:true})).toBeVisible();report.simulator=true;
  await page.getByRole('button',{name:'Switch to Arabic'}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');
  await page.screenshot({path:resolve(folder,'landing-arabic.png'),fullPage:true});report.rtl=true;
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(folder,'landing-mobile.png'),fullPage:true});
  report.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(report.mobileOverflow){console.log(await page.evaluate(()=>[...document.querySelectorAll('*')].map(element=>({tag:element.tagName,class:element.className,left:element.getBoundingClientRect().left,right:element.getBoundingClientRect().right})).filter(element=>element.left<-.5||element.right>innerWidth+.5)));throw new Error('Mobile landing page overflows horizontally.');}
  await page.getByRole('button',{name:'Switch to English'}).click();await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Open workspace',exact:true}).first().click();
  await page.getByRole('button',{name:/Inventory lead/}).click();
  await page.getByLabel('Corporate identity').fill('phase3_sales');await page.getByLabel('Password',{exact:true}).fill(process.env.SENTINEL_E2E_PASSWORD);
  await page.getByRole('button',{name:'Authenticate securely'}).click();
  await expect(page.getByRole('heading',{name:'Analytics workspace'})).toBeVisible();
  await expect(page.getByRole('button',{name:/Customer/}).first()).toBeVisible();
  await expect(page.getByRole('button',{name:/Track/})).toHaveCount(0);report.serverRoleIsolation=true;
  await page.getByLabel('Natural language request').fill('List customers in Brazil');await page.getByRole('button',{name:'Run query',exact:true}).click();
  await expect(page.getByRole('button',{name:'Export CSV'})).toBeEnabled({timeout:30000});
  await expect(page.locator('.intent-bar')).toContainText('Completed');report.websocket=true;
  await page.getByRole('tab',{name:'Verified SQL'}).click();await expect(page.locator('.studio-panel .sql-code')).toContainText('SELECT');
  await page.screenshot({path:resolve(folder,'workspace-desktop.png'),fullPage:true});
  const xlsxPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export Excel'}).click();const xlsx=await xlsxPromise;await xlsx.saveAs(resolve(root,'.runtime/export-check.xlsx'));
  const csvPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV'}).click();const csv=await csvPromise;await csv.saveAs(resolve(root,'.runtime/export-check.csv'));report.exports=true;
  const storage=await page.evaluate(()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage)}));
  if(storage.local.some(key=>key!=='sentinel-language')||storage.session.length)throw new Error('Unexpected persistent session storage.');report.memoryOnlySession=true;
  await page.getByRole('button',{name:'Switch to Arabic'}).click();await page.screenshot({path:resolve(folder,'workspace-arabic.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(folder,'workspace-mobile.png'),fullPage:true});
  report.workspaceMobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(report.workspaceMobileOverflow)throw new Error('Mobile workspace overflows horizontally.');
  await page.getByRole('button',{name:/Sign out|تسجيل الخروج/}).click();
  await page.getByRole('button',{name:'Switch to English'}).click();await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Open workspace',exact:true}).first().click();
  await page.getByLabel('Corporate identity').fill('phase3_inventory');await page.getByLabel('Password',{exact:true}).fill(process.env.SENTINEL_E2E_PASSWORD);
  await page.getByRole('button',{name:'Authenticate securely'}).click();await expect(page.getByRole('button',{name:/Track/}).first()).toBeVisible();await expect(page.getByRole('button',{name:/Customer/})).toHaveCount(0);
  await page.getByRole('button',{name:'REST',exact:true}).click();await page.getByLabel('Natural language request').fill('List rock tracks');await page.getByRole('button',{name:'Run query',exact:true}).click();await expect(page.getByRole('button',{name:'Export CSV'})).toBeEnabled({timeout:30000});report.rest=true;
  await page.getByRole('button',{name:'Sign out'}).click();
  report.browserErrors=errors;if(errors.length)throw new Error('Browser runtime errors: '+errors.join('; '));
  await fs.writeFile(resolve(root,'.runtime/browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){await page.screenshot({path:resolve(folder,'failure.png'),fullPage:true});throw error;}finally{await context.close();}
